#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

#####  ONLY CHANGE THIS BLOCK  ######
PROG=/tmp/sing-box/sing-box
RES_DIR=/tmp/sing-box/
CONF=./config.json   
#####  ONLY CHANGE THIS BLOCK  ######

start_service() {
    procd_open_instance
    procd_set_param command $PROG run -D $RES_DIR -c $CONF
    procd_set_param user root
    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="1000000 1000000"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_close_instance
    echo "sing-box is started!"
}

stop_service() {
    service_stop $PROG
    echo "sing-box is stopped!"
}

reload_service() {
    stop
    sleep 2s
    echo "sing-box is restarted!"
    start
}
